### ISSUE TITLE
Header 'TranslateCore-Swift.h' not found

### ISSUE THREAD

**Issue by tysun** [Lustres/Siri-Translate#1]
Hello

I would like to try Siri. But there is an error. 

` Header 'TranslateCore-Swift.h' not found`

What do you suggest?

Thanks!

**Comment by Lustres** [comment]
1. Switch to Scheme `TranslateCore`
2. Build It
3. Build project

Then the error will be gone. The framework must be built alone and firstly. (I think it's a bug in Xcode)

**Comment by tysun** [comment]
谢谢你的帮助
